### ISSUE TITLE
SQL Server Distributed cache with Managed Identity 

### ISSUE THREAD

**Issue by johnayoub** [aspnet/Extensions#1397] opened 2019-04-11 15:52 UTC
### Is your feature request related to a problem? Please describe.
Currently there's no way to use the distributed cache extension with managed identity as there's no way to pass an access token

### Describe the solution you'd like
Need the API the expose a way to allow for passing in the access token 

### Describe alternatives you've considered
Considered replacing the IDatabaseOperations class but that class is marked as internal

Any ideas on how to accomplish this would be helpful

**Comment by johnayoub** [comment] 2019-04-11 20:00
I have created a pull request for this: https://github.com/aspnet/Extensions/pull/1400

**Comment by anurse** [comment] 2019-06-26 21:27
Going to close this as a duplicate of https://github.com/aspnet/Extensions/issues/1142

**Closed by anurse** 2019-06-26 21:27 UTC
Labels: area-caching
