### ISSUE TITLE
Packaging error: Invalid nuget package with 2 identical files created

### ISSUE THREAD

**Issue by Flohack74** [aspnet/Extensions#2744] opened 2019-12-04 15:59 UTC
### Describe the bug
See https://github.com/fsprojects/Paket/issues/3743 - Currently one or many projects that were pushed in the last 24hrs seem to have lliegal content in the ZIP file, creating issues with compression libs. Specifically, the packaged icon is duplicated. See screenshot

### To Reproduce
1. Just download nupkg file and inspect visually
2. See error

### Screenshots
![grafik](https://user-images.githubusercontent.com/16186470/70158308-517a0980-16b7-11ea-9905-218694c4dcb7.png)

### Additional context
While the paket guys implemented a fix for that, this should be investigated thoroughly, as it seems to hit multiple packaging jobs not connected to the same namespace.

**Comment by slang25** [comment] 2019-12-04 16:07
I've confirmed by checking out `release/3.1` and running:
```
./build.sh
unzip -l ./artifacts/packages/Debug/Shipping/Microsoft.Extensions.DependencyInjection.Abstractions.3.1.0.zip
```

you'll see 2 x `packageIcon.png`.

**Comment by forki** [comment] 2019-12-04 16:26
There are multiple packages in the 3.1 release cycle witu this issue. It seems to be a systematic issue somewhere in packaging.

**Comment by rrelyea** [comment] 2019-12-04 17:42
From internal email thread:
This doesn’t seem to reproduce the problem of duplicate embedded icons:

Md paket-2019-12-break
Cd packet-2019-12-break
Dotnet new classlib
Create packageicon.jpg and packageicon2.jpg

Modify project file to be:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>paket_2019_12_break</RootNamespace>
    <PackageIcon>packageicon.jpg</PackageIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Include="packageicon.jpg" Pack="true" PackagePath="\" />
    <None Include="packageicon2.jpg" Pack="true" PackagePath="\packageicon.jpg" />
  </ItemGroup>
</Project>

```

Dotnet pack

actual behavior: only one packageicon.jpg entry (as viewed via 7-zip)

**Comment by dougbu** [comment] 2019-12-04 18:39
+ @aspnet/build 

@rrelyea we got into this situation in two steps
1. Update all ASP.NET Core repos to **manually** include embedded icons with the correct NuGet metadata
2. Upgrade the Arcade SDK to a version which centralized all the logic, adding overlapping metadata and icon files

@wtgodbe didn't you fix all of our repos up to use _only_ the Arcade SDK logic? Did merges forward into our 3.1 branches just miss the boat on the GA release?

**Comment by wtgodbe** [comment] 2019-12-04 18:41
@dougbu I did fix this, but it didn't get merged forward for 3.1.0. The fixes are in 3.1.1 and master now, though.

**Comment by dougbu** [comment] 2019-12-04 19:00
@rrelyea @Pilchie is 3.1.1 soon enough from your perspectives?

For one thing, how many customers do we have using these packages with 3rd party clients?

**Comment by rrelyea** [comment] 2019-12-04 19:08
Given that 3.1.0 package already shipped. We need to understand if having a 3.1.1 package with the fix will help fix the issue for most people.
That depends on the scenario of how people decide to download 3.1.0.

If they pick it because it is hardcoded into a template, then the fix won't be too helpful.
If most people pick it because an update to their current 3.0 package via NuGet Update tab in VS, then fixing it now would help people avoid it.

We also should understand which scenarios are hurt by it.  Just Paket? Other?

Paket? all Versions? How often do paket users upgrade to latest, etc... - @forki and team can likely help us understand impact of their user base and importance of fixed packages - now or in about a month?

**Comment by forki** [comment] 2019-12-04 19:17
From Paket perspective: workaround is applied and a new Paket version is available. Usually this means the problem is gone next day because our user base is mostly running on the latest Paket. So if the problem is identified then I don't think 3.1.1 packages are really needed to be pushed immediately. At least not from our perspective. But I think nuget team should add an additional check for duplicates in package verification. This would prevent similar issues in the future

**Comment by rrelyea** [comment] 2019-12-04 21:54
By the way, if somebody is using a nuspec, it is possible to have duplicate items in a nupkg: https://github.com/NuGet/Home/issues/6941

**Comment by Fido789** [comment] 2019-12-12 10:14
I would prefer 3.1.1 versions of affected packages ASAP as this issue block us from pushing them to private NuGet server. The server is returning status 406 (not accepted).

**Comment by forki** [comment] 2019-12-12 10:17
@Fido789 which private NuGet server implementation do you use?

**Comment by Fido789** [comment] 2019-12-12 10:21
@forki I have tried it with https://www.nuget.org/packages/NuGet.Server/3.1.2 and https://www.nuget.org/packages/NuGet.Server/3.4.1

**Comment by forki** [comment] 2019-12-12 10:26
Wow. So private installation of nuget is rejecting the packages but the public server did not?

**Comment by rrelyea** [comment] 2019-12-12 17:23
NuGetGallery and NuGet.Server are two different codebases. Not surprising that their behavior differs a bit here. @joelverhagen

**Comment by ajcvickers** [comment] 2019-12-12 19:16
@Pilchie Should this issue be triaged into a milestone and assigned to someone so that people can track the status?

**Comment by forki** [comment] 2019-12-12 19:20
If nuget's own private server implementation is rejecting the packages and Paket did, then chances are other 3rd-party servers and tools will do as well.

**Comment by Pilchie** [comment] 2019-12-12 19:31
I believe this is already fixed in `3.1.1`.  @wtgodbe can you confirm?

**Comment by wtgodbe** [comment] 2019-12-12 19:40
@Pilchie that's correct, this is fixed for 3.1.1.

**Closed by wtgodbe** 2019-12-12 19:40 UTC
Labels: area-infrastructure

**Comment by forki** [comment] 2019-12-12 19:42
@Pilchie are those packages already available? Will the broken ones be unlisted? And then there is the problem of nuget's behavior with unlisted packages. If it's a transitive dependency then nuget will continue to install 3.1.0 because of it's minimum matching version resolver. Even if that package is unlisted.
So you'd would need to roll out the full wave of 3.1.1. Even with packages that are not broken but depend on a broken package.

**Comment by Pilchie** [comment] 2019-12-12 19:44
No, the packages are not available yet, we're still working through issues with preparing 3.1.1 all-up.  I don't expect they will be released before the new year unfortunately.

**Comment by forki** [comment] 2019-12-12 19:50
Butbwhy can't you push a wave of packages that just fix this specific issue? As more and more people are moving to 3.1 this will be getting more serious.

**Comment by Pilchie** [comment] 2019-12-12 19:50
That's just not the way our infrastructure is set up unfortunately.

**Comment by willsmith9182** [comment] 2020-01-03 17:43
Any news on this or an eta for relelase?

I'm allergic to build warnings when restoring packages

**Comment by dougbu** [comment] 2020-01-03 20:43
The next patch release (3.1.1) includes a fix for this issue. We're working to get that release out soon.

**Comment by daconglee** [comment] 2020-01-06 13:15
Verbose: File system changed. File: microsoft.extensions.configuration.3.1.0.nupkg - Change: Changed
Info: Start adding packages from drop folder.
Error: An exception occurred while handling a file system event: System.ArgumentException: Item has already been added. Key in dictionary: 'packageIcon.png'  Key being added: 'packageIcon.png'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
