### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Extensions#595] opened 2018-12-06 23:50 UTC
This build: https://dnceng.visualstudio.com/public/_build/results?buildId=53775

```
2018-12-06T19:51:32.2541617Z   [xUnit.net 00:00:53.75]     Microsoft.Extensions.Configuration.Test.ConfigurationTests.DeletingFilesThatRedefineKeysWithReload(optional: False) [FAIL]
2018-12-06T19:51:32.2787685Z   Failed   Microsoft.Extensions.Configuration.Test.ConfigurationTests.DeletingFilesThatRedefineKeysWithReload(optional: False)
2018-12-06T19:51:32.2836421Z   Error Message:
2018-12-06T19:51:32.2836615Z    Assert.Equal() Failure
2018-12-06T19:51:32.2836756Z              (pos 0)
2018-12-06T19:51:32.2836892Z   Expected: IniValue1
2018-12-06T19:51:32.2850567Z   Actual:   JsonValue1
2018-12-06T19:51:32.2948189Z              (pos 0)
2018-12-06T19:51:32.2985934Z   Stack Trace:
2018-12-06T19:51:32.2988386Z      at Microsoft.Extensions.Configuration.Test.ConfigurationTests.DeletingFilesThatRedefineKeysWithReload(Boolean optional) in /_/src/Configuration/test/Config.FunctionalTests/ConfigurationTests.cs:line 687
2018-12-06T19:51:32.2990054Z   --- End of stack trace from previous location where exception was thrown ---
```

**Comment by ajcvickers** [comment] 2018-12-08 22:41
Duplicate of https://github.com/aspnet/AspNetCore-Internal/issues/1319

**Closed by ajcvickers** 2018-12-08 22:41 UTC
