### ISSUE TITLE
[Mac]Double click .exe file in publish folder, the page shown in the browser doesn't correctly.

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Extensions#2386] opened 2019-09-23 22:00 UTC
_From @v-jiaxi on Friday, September 20, 2019 4:00:37 AM_

**Repro Configuration**: osx-10.14-x64 +VS Code +3.0 GA +Feed
**.NET Core SDK (CLI) Version**: 3.0.100
**.NET Core runtime Version**: 3.0.0

**Testcases Affected**: Using the exe file directly to run the app
**Regression Info**: Not a regression

**Install Steps**
1. Install 3.0 GA build (3.0.100-rc2-014277) from:  vsufile/patches/sign/NET/CORE_BUILDS/3.0.X/3.0.0/final/3.0.100-rc2-014277/shipping/assets/Sdk\3.0.100/dotnet-sdk-3.0.100-osx-x64.pkg
1. add feed: 
https://pkgs.dev.azure.com/dnceng/public/_packaging/3.0.100-rc2-014277/nuget/v3/index.json

**Repro Steps**
1. Open a Terminal window
2. Run :
 ``` 
mkdir webapp
cd webapp
dotnet new razor
 ```
3. Publish to folder:
```
dotnet publish -c release
cd ./bin/release/netcoreapp3.0/publish/ 
open .    
```
4. Double click webapp.exe in published folder. Open a browser and navigate to https://localhost:500. The page show in the browser doesn't correctly.

**Note:** It doesn't repro on Windows.

**ACTUAL**
![image](https://user-images.githubusercontent.com/43693637/65296568-7ae6c700-db97-11e9-9933-55a992856420.png)

_Copied from original issue: aspnet/AspNetCore-ManualTests#22_

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @ajaybhargavb on Friday, September 20, 2019 4:58:10 PM_

Related issue which was closed by design. But this only happens on a mac so this is definitely a bug. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/943535

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @mkArtakMSFT on Friday, September 20, 2019 8:26:47 PM_

@ajaybhargavb can you please try this out? Thanks!

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @ajaybhargavb on Friday, September 20, 2019 9:08:02 PM_

I tried this and I can reproduce it.

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @ajaybhargavb on Friday, September 20, 2019 9:14:16 PM_

I can see that the content root path is set to the user profile folder on mac,
![image](https://user-images.githubusercontent.com/1579269/65359263-dec9b980-dbb0-11e9-9f57-7c129ecf1fb1.png)

whereas in windows it is set correctly to the publish folder,
![image](https://user-images.githubusercontent.com/1579269/65359314-fe60e200-dbb0-11e9-950c-edafd59ba88a.png)

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @ajaybhargavb on Friday, September 20, 2019 9:16:34 PM_

@javiercn, any ideas why this could be happening on a Mac but not on Windows?

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @javiercn on Friday, September 20, 2019 9:43:29 PM_

That sounds like a bad CLR/Hosting bug. @tratcher @davifowl ideas?

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @Tratcher on Friday, September 20, 2019 9:49:27 PM_

https://github.com/aspnet/Extensions/blob/7433e7f07cceb73410d6bdb0a1ffd5be6ccb23b7/src/Hosting/Hosting/src/Host.cs#L60
What's  `Directory.GetCurrentDirectory()` on mac for this scenario?

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @ajaybhargavb on Friday, September 20, 2019 10:00:13 PM_

> What's Directory.GetCurrentDirectory() on mac for this scenario?

Yes, that returns `/Users/ajbaaska`

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @Tratcher on Friday, September 20, 2019 10:08:00 PM_

And it works when you start it from the command line?

Seems like an issue with GetCurrentDirectory.

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @ajaybhargavb on Friday, September 20, 2019 10:30:21 PM_

> And it works when you start it from the command line?

It works when I `dotnet run`. But not when I publish and use the executable.

> Seems like an issue with GetCurrentDirectory

Do you mean the current working directory is not set correctly? Who should be looking into this?

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @Tratcher on Friday, September 20, 2019 10:31:55 PM_

CoreFx

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @ajaybhargavb on Monday, September 23, 2019 7:02:14 PM_

@Tratcher, I tried to get a more minimal repro of this but couldn't reproduce this issue with a console app. When I publish and run a console app, `Directory.GetCurrentDirectory()` is properly set on both Windows and Mac. This only seems to happen when our hosting is involved. Am I missing something here?

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @ajaybhargavb on Monday, September 23, 2019 8:10:35 PM_

Spoke offline. I can repro it when I double click the executable.

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @ajaybhargavb on Monday, September 23, 2019 8:14:29 PM_

Tracking this in https://github.com/dotnet/corefx/issues/41267.

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @ajaybhargavb on Monday, September 23, 2019 9:24:00 PM_

@Tratcher @mkArtakMSFT  https://github.com/dotnet/coreclr/issues/26844 was closed as by design. Do we plan to do anything to workaround it? Or are we okay with this behavior?

**Comment by Tratcher** [comment] 2019-09-23 22:00
_From @Tratcher on Monday, September 23, 2019 9:33:02 PM_

No, we're not OK with this behavior, it breaks apps. `Directory.GetCurrentDirectory()` is unreliable and we'll have to redesign to avoid using it.

I'll move this over to Extensions Hosting.

**Comment by anurse** [comment] 2019-09-24 23:02
We depend on the current directory to locate the static web contents. On macOS, when launching in finder, the current directory is set to the user profile. We can do a little thinking about design but I don't know that this is a high priority. Since this was ported from our ManualTests repo, do we know if customers are hitting this problem?

**Comment by v-jiaxi** [comment] 2019-10-21 06:14
Navigate to Develop > Show JavaScript Console. There are some errors below:
![image](https://user-images.githubusercontent.com/43693637/67180726-0492ea00-f40d-11e9-8988-858673d46644.png)

**Comment by anurse** [comment] 2019-11-07 23:57
My feeling is that we should just remove this scenario from the test script. It's been like this for a while and we haven't heard from customers. Instead, the app should be launched from the command-line, while in the publish directory.

The content root has been like this since 1.0 (based off current directory) so I'm not sure there's a big motivation to change this. Thoughts @davidfowl @javiercn @Tratcher ?

**Comment by davidfowl** [comment] 2019-11-08 07:34
Agree

**Comment by javiercn** [comment] 2019-11-08 08:38
Super agree

**Comment by anurse** [comment] 2019-11-08 19:45
Ok, filed a bug in the CTI repo for that. Closing this as by design now.

**Closed by anurse** 2019-11-08 19:45 UTC
Labels: area-hosting
