### ISSUE TITLE
.UseSystemd() issue when trying to stop service via command line.

### ISSUE THREAD

**Issue by speed2048** [aspnet/Extensions#2761] opened 2019-12-05 21:39 UTC
### Describe the bug
I have created  a Linux Worker and use .UseSystemd(). The system starts correctly however if I stop the service there is a delay between 1 - 2 minutes before the service actually stops. 

### To Reproduce
1. Using version V3.1.0 of package Microsoft.Extensions.Hosting.Systemd and Microsoft.Extensions.Hosting.

2. Run this code Systemd code with the following code snippet.

 _protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{ 
      while (!stoppingToken.IsCancellationRequested)
        {
              ...dostuff
              await Task.Delay(1 * 1000, stoppingToken);
         }
}_
create a unit file and run it as a system service
service Test.Service start.

service Test.Service stop.

The stop service command  will take about a minute to return to the command prompt.

4. The following log file entry shows in the delay of stopping the service.

Dec 04 16:32:43 raspberrypi-4 systemd[1]: Starting Test.Service.
Dec 04 16:32:58 raspberrypi-4 systemd[1]: Started Test.Service
Dec 04 16:33:02 raspberrypi-4 Test.Service[23294]: Starting Test.Service 4.0.0.152 at 2019-12-04
Dec 04 16:33:05 raspberrypi-4 Test.Service[23294]: Microsoft.Hosting.Lifetime[0] Application started. Hosting en
Dec 04 16:33:53 raspberrypi-4 Test.Service[23294]: Microsoft.Hosting.Lifetime[0] Application is shutting down...
_**Dec 04 16:33:53** raspberrypi-4 Test.Service[23294]: A task was canceled.
**Dec 04 16:35:13** raspberrypi-4 systemd[1]: Test.Service: Succeeded._

Noticed the highlighted time that it took to exit and the time the task was canceled message was triggered.

### Expected behavior
The service test.service stop should return immediately. 

### Additional context

Issue does not occur if on a windows platform using  .UseWindowsService().
Happens on  linux-arm and linux-64 platforms.
Using PublishingSingleFile is set to true.

 dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.109 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
 
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsof
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Tratcher** [comment] 2019-12-06 19:21
What happens if you run it as an interactive console app on linux?

Do you have logs inside that while loop showing its running? Where did the "A task was canceled." log come from?

**Comment by speed2048** [comment] 2019-12-06 21:14
If I run it as an interactive console app on linux and hit control c. The following messages are displayed.

Starting Test.Service 4.0.0.152 at 12/6/2019 12:41:15 PM
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/ubuntu/test/bin
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
A task was canceled.
info: Microsoft.Hosting.Lifetime[0]
      Waiting for the host to be disposed. Ensure all 'IHost' instances are wrapped in 'using' blocks.

And in this case I have to kill the process to exit. And when I do that I get a Killed message.

I have no idea where the 'A task was canceled.' is coming from I looked in my code and found no references to canceled.   I also looked  in the aspnet/extensions github project and also found no references.
 
Yes I have log files indicating when it is running or not... If I get to the Application is shutting down message the service no longer is running and waiting to exit.

**Comment by speed2048** [comment] 2019-12-07 07:47
I did some more testing. I used the blank dotnet new worker template and executed on linux and it does NOT exhibit the ~ one minute delay.

After reviewing my code and  github net core  runtime I believe it has to be related to linq queries while executing in the while loop. I have found there a definition of a  63 second polling loop in System.Linq.Parallel.Scheduling.CancellationState.cs  and  implemented in System.Linq.Parallel.Utils.CancellableEnumerable.cs

However I am not using PLINQ so not sure why this would be executed unless my LINQ would some how be calling the parallel version.

Should I convert my LINQ to PLINQ or is this still an issue?

Note I also found where the 'A task was canceled' is used / defined.

System.Threading.Tasks.TaskCancelException.cs

**Comment by speed2048** [comment] 2019-12-07 18:25
Found out why the code was waiting for a minute before exiting the service as well as why the following message occurred if I ran the application from the command line.

 **Waiting for the host to be disposed. Ensure all 'IHost' instances are wrapped in 'using' blocks.**

If I have a Environment.Exit() in the finally block. It will cause theses issues.

I have removed this from my code and it is working correctly, however if I needed to return a status code back to the calling application this would be an issue.

See attached code,

[worker.zip](https://github.com/aspnet/Extensions/files/3935408/worker.zip)

**Comment by halter73** [comment] 2019-12-12 23:25
> If I have a Environment.Exit() in the finally block. It will cause theses issues.
>
> I have removed this from my code and it is working correctly, however if I needed to return a status code back to the calling application this would be an issue.

You don't need to use Environment.Exit() to set an exit code. You can return an int from Program.Main().

**Comment by anurse** [comment] 2019-12-18 21:45
As @halter73 said, `Environment.Exit` isn't needed to set the exit code. It also skips disposing the host which causes this known hang. https://github.com/aspnet/Extensions/issues/2030 is tracking a longer-term fix for this. If you are able to stop using Environment.Exit, that would be the best solution for you in this case.

**Comment by speed2048** [comment] 2019-12-19 05:01
Yes avoiding Environment.Exit works for me.  

Thanks.

**Comment by anurse** [comment] 2019-12-19 16:19
Closing this as a duplicate of #2030 then. That's still the main underlying issue here.

**Closed** 2019-12-19 16:19 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Needs: Attention :wave:, Status: Resolved, area-hosting
