### ISSUE TITLE
SqlServer cache cleanup silently fails on timeout

### ISSUE THREAD

**Issue by Fraaankes** [aspnet/Extensions#981] opened 2019-01-21 17:17 UTC
We are using the SqlServer cache as the backing for our IDistributed session storage, and noticed that we started to see "random" hangs of the application every 30 minutes (the default cleanup interrval).
New requests comming in would be blocked, and executing ones would time out trying to access the session.

It looks like this behaviour is caused by the `DBOperation.DeleteExpiredCacheItems` being triggered on a new fire-and-forget task, and if it hits the default 30s SQL command timeout it will issue a rollback of the delete, taking out a lock on the entire table, blocking everything else.

Being unable to run the cleanup, also means that DB storage usage will start growing out of control:
[Screenshot of DB size](https://imgur.com/a/0fx2BIO)

### Expected behavior
The cleanup job doesnt silently fail, and perhaps a way to specify the command timeout for this one particular operation

### Additional context
SQL server is an Azure DB on tier S3 (100 DTU)

**Comment by Fraaankes** [comment] 2019-01-21 21:11
So far i have managed to do a dirty workaround by doing the following
```
public class NoCleanUpSqlServerCache : IDistributedCache
    {
        private readonly SqlServerCache inner;
        public NoCleanUpSqlServerCache(IOptions<SqlServerCacheOptions> options)
        {
            inner = new SqlServerCache(options);
            RemoveCleanup();
        }
        private void RemoveCleanup()
        {
            const string name = "_deleteExpiredCachedItemsDelegate";
            var field = inner.GetType().GetField(name, BindingFlags.GetField | BindingFlags.NonPublic | BindingFlags.Instance);
            if (field == null)
            {
                throw new ArgumentException($"Could not find delegate field {name}");
            }
            Action noop = DoNothing;
            field.SetValue(inner, noop);
        }
        private static void DoNothing()
        {
            Debug.WriteLine("Doing nothing triggered by framework");
        }

        ... Delegating all interface methods to inner

     public class SqlCleanupHostedService : IHostedService
        {
            private const int BatchLimit = 1000;
            private readonly IOptions<SqlServerCacheOptions> options;
            private Timer timer;
            public SqlCleanupHostedService(IOptions<SqlServerCacheOptions> options)
            {
                this.options = options;
            }
            public Task StartAsync(CancellationToken cancellationToken)
            {
                timer = new Timer(CleanUp, null, TimeSpan.Zero, TimeSpan.FromSeconds(30));
                return Task.CompletedTask;
            }
            public Task StopAsync(CancellationToken cancellationToken)
            {
                timer?.Change(Timeout.Infinite, 0);
                return Task.CompletedTask;
            }
            private void CleanUp(object state)
            {
                var utcNow = DateTime.UtcNow;
                var tableNameWithSchema = $"{DelimitIdentifier(options.Value.SchemaName)}.{DelimitIdentifier(options.Value.TableName)}";
                using (var conn = new SqlConnection(options.Value.ConnectionString))
                {
                    conn.Open();
                    using (var cmd = conn.CreateCommand())
                    {
                        var sql = $"DELETE FROM {tableNameWithSchema} WHERE Id IN (SELECT TOP (@top) Id FROM {tableNameWithSchema} WHERE @utcNow > ExpiresAtTime)";
                        cmd.CommandText = sql;
                        cmd.Parameters.AddWithValue("@utcNow", utcNow);
                        cmd.Parameters.AddWithValue("@top", BatchLimit);
                        cmd.ExecuteNonQuery();
                    }
                }
            }
            private static string DelimitIdentifier(string identifier)
            {
                return "[" + identifier.Replace("]", "]]") + "]";
            }
        }
    }

}
```
and then replacing in `startup.cs`
```
    services.AddDistributedSqlServerCache(options =>
    {});
```
with 
```
       services.AddSingleton<IDistributedCache, NoCleanUpSqlServerCache>();
       services.AddHostedService<NoCleanUpSqlServerCache.SqlCleanupHostedService>();
```

**Comment by epignosisx** [comment] 2019-01-21 23:15
Issue #492 describes a different query to perform the clean up. It has better chances of avoiding a table lock.

How many rows do you have in the table? How big is the data you are storing? 

We were running into a lot of deadlocks and we did a couple of things:

1- Gzip content before inserting
2- Changed the database isolation level to SNAPSHOT

You might want to consider these as well.

**Comment by Fraaankes** [comment] 2019-01-22 21:21
Thank you for the suggestions.
Im already zipping up most of the data before storing it, so an average cache key value is around 14255 bytes.
This could maybe be impoved upon a bit.
And at peak times there is perhaps around 150.000 rows in the table, but im sure this number will only go up, as more things finds it way into the cache.

**Comment by anurse** [comment] 2019-06-26 23:16
This appears to be a duplicate of https://github.com/aspnet/Extensions/issues/492. Let us know if that's wrong!

**Closed by anurse** 2019-06-26 23:16 UTC
Labels: area-caching
