### ISSUE TITLE
ValidateDataAnnotations throws exception on invalid options but has no details in message

### ISSUE THREAD

**Issue by dshamim** [aspnet/Extensions#979] opened 2019-01-21 00:54 UTC
### Describe the bug
I have tried using the new ValidateDataAnnotations to validate options -I'm not sure if this would be a bug or feature to add, but when the configuration is invalid based on data annotations in the options class - it throws the OptionsValidationsException but there's no context / message as to what's exactly missing - would it be possible to add validation error messages as part of the exception ?

in contrast, if I use the Validator.TryValidateObject , I at least get a list of validation errors - can these be concatenated and added to the OptionsValidationsException message  ?

### To Reproduce
1. Using Microsoft.Extensions.Options.DataAnnotations.ValidateDataAnnotations
2. Sample call: `services.AddOptions<PricingTargetOptions>()
                .Bind(Configuration.GetSection("EmailReports:PricingTarget"))
                .ValidateDataAnnotations();` 
3. Run with missing required values in appsettings.json
4. See error when accessing injected options value

### Expected behavior
There should be some context on why OptionsValidationException was thrown, on which field etc.

### Additional context
Include the output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by ajcvickers** [comment] 2019-01-23 01:37
@HaoK Thoughts?

**Comment by HaoK** [comment] 2019-01-23 01:55
Yeah seems like an easy change, I think we've gotten this feedback a few times already, dupe of https://github.com/aspnet/Extensions/issues/904 probably

**Comment by ajcvickers** [comment] 2019-04-18 16:35
@HaoK I put this in 6 for now; it seems like a high value simple change that has been asked for multiple times.

**Comment by HaoK** [comment] 2019-06-03 20:30
People keep hitting this, should definitely get this in for preview7

**Closed** 2019-06-05 22:52 UTC
Labels: PRI: 2 - Preferred, area-options
