### ISSUE TITLE
It's impossible to log in HostBuilder.ConfigureServices

### ISSUE THREAD

**Issue by ststeiger** [aspnet/Extensions#2553] opened 2019-10-23 09:24 UTC
I have a Windows and Linux Service, see code below. 

Now in 
`        .ConfigureServices(delegate (HostBuilderContext hostContext, IServiceCollection services)`
which doesn't take an ILogger<Program> as argument, I have the following code:

`Configuration.FullConfiguration fullConfig = ConfigurationHelpers.GetConfig();`

Now, getconfig gets the values, and validates them. 
How do I get an ILogger in ConfigureServices ? 

Also, how do I get IConfiguration in ConfigureServices  ? 

Since HostBuilder doesn't contain UseStartup - this is near hopeless...

How is this supposed to work ? 

```

// https://wakeupandcode.com/generic-host-builder-in-asp-net-core/
Microsoft.Extensions.Hosting.IHostBuilder builder =
    new Microsoft.Extensions.Hosting.HostBuilder()
        // .UseMyStartup(args)
        // https://github.com/aspnet/AspNetCore.Docs/issues/9278
        //.ConfigureHostConfiguration(configHost =>
        .ConfigureHostConfiguration(delegate (IConfigurationBuilder configHost)
        {
            configHost.SetBasePath(System.IO.Directory.GetCurrentDirectory());
            configHost.AddJsonFile("hostsettings.json", optional: true);
            configHost.AddEnvironmentVariables(prefix: "PREFIX_");
            configHost.AddCommandLine(args);
        })
        //.ConfigureAppConfiguration((hostContext, configApp) =>
        .ConfigureAppConfiguration(delegate (HostBuilderContext hostContext, IConfigurationBuilder configApp)
        {
            string dir = System.IO.Path.GetDirectoryName(typeof(Program).Assembly.Location);
            // dir = System.IO.Directory.GetCurrentDirectory();
            configApp.SetBasePath(dir);

            configApp.AddJsonFile("appsettings.json", optional: true);
            configApp.AddJsonFile(
                $"appsettings.{hostContext.HostingEnvironment.EnvironmentName}.json",
                optional: true);
            configApp.AddEnvironmentVariables(prefix: "PREFIX_");
            configApp.AddCommandLine(args);
        })
        //.ConfigureLogging((hostContext, configLogging) =>
        .ConfigureLogging(delegate (HostBuilderContext hostContext, ILoggingBuilder configLogging)
        {
            // https://www.codeproject.com/Articles/1556475/How-to-Write-a-Custom-Logging-Provider-in-ASP-NET

            // string dir = System.IO.Path.GetDirectoryName(typeof(Program).Assembly.Location);
            // string logDir = System.IO.Directory.GetCurrentDirectory();
            string logDir = System.IO.Path.GetDirectoryName(typeof(Program).Assembly.Location);
                        
            logDir = System.IO.Path.Combine(logDir, "Log");
            if (!System.IO.Directory.Exists(logDir))
                System.IO.Directory.CreateDirectory(logDir);


            configLogging.AddFileLogger(
                delegate (LdapService.Helpers.Log2.FileLoggerOptions fo)
                {
                    fo.Folder = logDir;
                    fo.LogLevel = LogLevel.Trace;
                }
            );


            /*
            configLogging.AddFile();
            configLogging.Services.Configure<FileLoggerOptions>(
                delegate (FileLoggerOptions flo)
                {
                    // FileLoggerOptions flo = new FileLoggerOptions();
                    flo.LogDirectory = null;
                    // flo.LogDirectory = "";
                    flo.FileName = "lol_log.txt";
                    flo.IsEnabled = true;
                    flo.BatchSize = 1;
                }
            );
            */

            configLogging.SetMinimumLevel(LogLevel.Information);
            configLogging.AddFilter(x => x >= LogLevel.Trace);

            configLogging.AddConsole();
            configLogging.AddDebug();
        })
        .ConfigureServices(delegate (HostBuilderContext hostContext, IServiceCollection services)
        {
            // https://github.com/aspnet/Logging/issues/361

            // services.AddHostedService<LdapService.LDAPservice>();
            // services.AddHostedService<FileWriterService>();

            Configuration.FullConfiguration fullConfig = ConfigurationHelpers.GetConfig();
            services.AddSingleton(fullConfig);

            services.AddHostedService<NewLdapService>();
        }
);


if (isService)
{
    await builder.RunAsServiceAsync();
}
else
{
    await builder.RunConsoleAsync();
}
```

**Comment by davidfowl** [comment] 2019-10-27 01:27
> How do I get an ILogger in ConfigureServices ?

You can't today. If you need to log before the host is configured then you can create a separate logger.

> Also, how do I get IConfiguration in ConfigureServices ?

The HostBuilderContext has a Configuration object on it.

> Since HostBuilder doesn't contain UseStartup - this is near hopeless...

UseStartup doesn't help, the same constraints exist in ASP.NET Core applications in 3.0.

You have 2 options:
- Defer your configuration logic until resolution time (use more funcs in the DI container). That would change this line to look more like this:
    ```C#
            services.AddSingleton(sp => {
                // TODO: Resolve logger here
                return ConfigurationHelpers.GetConfig();
            });
    ```
- Configure logging outside of the Host and give the host a logger. There are some downsides to this but if you need to log earlier then there's no workaround.

**Comment by Tratcher** [comment] 2019-10-27 01:35
This is mostly a duplicate of https://github.com/aspnet/AspNetCore/issues/9337.

**Comment by anurse** [comment] 2019-11-07 19:59
Closing as logging was intentionally moved in to the DI configuration. @davidfowl gave some workarounds but at this time we don't plan on changing this model when using Generic Host.

**Closed by anurse** 2019-11-07 19:59 UTC
Labels: area-hosting
