### ISSUE TITLE
Last modification times are missing for all extension DLLs

### ISSUE THREAD

**Issue by hikalkan** [aspnet/Extensions#2774] opened 2019-12-11 14:22 UTC
Last modification time of all Microsoft.Extensions.*.dll files are missing in v3.1. It was not empty in v3.0.

This causes error while I want to create a DotNet Global Tool NuGet Package:

````
C:\Program Files\dotnet\sdk\3.1.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error : The DateTimeOffset specified cannot be converted into a Zip file timestamp. (Parameter 'value') [D:\Github\abp\framework\src\Volo.Abp.Cli\Volo.Abp.Cli.csproj]
````

I modified last modification times of all dll files (under C:\Users\my-username\\.nuget\packages folder) manually (OK, I used http://www.nirsoft.net/utils/bulk_file_changer.html) and the error has been fixed.

**Comment by Pilchie** [comment] 2019-12-11 17:05
This is a duplicate of https://github.com/aspnet/Extensions/issues/2750

**Closed** 2019-12-12 18:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-infrastructure

**Comment by Maleaume** [comment] 2019-12-14 23:43
Last modification time of all Microsoft.Extensions.*.dll files are missing in v3.1
I have make a test with EF Core in project A.
a project B referenced the Package A. 
I'm using 
`<TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>`

and 

```
<Target DependsOnTargets="ResolveReferences" Name="CopyProjectReferencesToPackage">
    <ItemGroup>
      <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths-&gt;WithMetadataValue('ReferenceSourceTarget', 'ProjectReference'))" />
    </ItemGroup>
  </Target>
```
 

Error during publish: 
The DateTimeOffset specified cannot be converted into a Zip file timestamp.
```
 System.AggregateException: One or more errors occurred. ---> System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__213.MoveNext()
---> (Inner Exception #0) System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---

System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. `
```

**Comment by ahmetaltay33** [comment] 2020-01-10 12:06
I have the same problem. When i execute dotnet pack command for dotnet global tool project then i get this message "C:\Program Files\dotnet\sdk\3.1.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error : The DateTimeOffset specified cannot be converted into a Zip file timestamp. (Parameter 'value') [D:\CodeGenProj\src\CodeGenerator.csproj]"
