### ISSUE TITLE
weird cancellation behavior

### ISSUE THREAD

**Issue by cyberhck** [aspnet/Extensions#2565] opened 2019-10-26 05:54 UTC
### Describe the bug
I've a worker service on my .NET application which runs as long as application is running. From templates, I got to the following simplified code:
```c#
namespace Micro.KeyStore.Api.Workers
{
    public class CleanupKeysWorker : BackgroundService
    {
        private readonly ILogger<CleanupKeysWorker> _logger;
        private readonly IKeyRepository _keyRepository;
        private readonly IDriver<Key> _archiver;
        private readonly ArchiveKeysConfig _config;

        public CleanupKeysWorker(ILogger<CleanupKeysWorker> logger, IServiceScopeFactory serviceScopeFactory, IDriver<Key> archiver, IOptions<ArchiveKeysConfig> config)
        {
            _logger = logger;
            _archiver = archiver;
            _config = config.Value;
            _keyRepository = serviceScopeFactory.CreateScope().ServiceProvider.GetRequiredService<IKeyRepository>();
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            try
            {
                while (!stoppingToken.IsCancellationRequested)
                {
                    var keys = await _keyRepository.FindCreatedBefore(
                        DateTime.Now.Subtract(TimeSpan.FromMinutes(_config.TimeToLiveInMinutes)), 100); // 100 is batch size, so it'd return 100 keys
                    foreach (var key in keys)
                    {
                        // make a api request, for simulation, let's do a Thread.Sleep without cancellation token
                       Thread.Sleep(500);
                    }

                    _logger.LogInformation($"Archived {keys.Count()} keys at {DateTime.Now}");
                    // I also tried doing: if (stoppingToken.IsCancellationRequested) return;
                    await Task.Delay(TimeSpan.FromSeconds(_config.BatchIntervalInSeconds), stoppingToken);
                }
            }
            catch (OperationCanceledException e)
            {
                // do nothing
            }
        }
    }
}

```

### To Reproduce
Run the above code, if we press <kbd>Ctrl</kbd> + <kbd>C</kbd> as soon as it logs `Archived 100 keys at {Time}`, everything works fine, but if we press <kbd>Ctrl</kbd> + <kbd>C</kbd> before that happens (while it's still inside the loop), it throws the following exception once it completes the current loop:
```
Unhandled exception. System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Micro.KeyStore.Api.Program.Main(String[] args) in /home/ngautam/git/personal/microservices/Micro.KeyStore/Micro.KeyStore.Api/Program.cs:line 24
```

### Expected behavior
Since I have cancellation token, it should not throw exception, rather it should stop with 0 status code (also notice the commend where I simply did a return if cancellation was requested)

### Screenshots
![image](https://user-images.githubusercontent.com/3640284/67614945-aa6c9d00-f7ef-11e9-9e1d-1a42442a0acb.png)

![image](https://user-images.githubusercontent.com/3640284/67614949-bbb5a980-f7ef-11e9-85b6-26dd21fb76f3.png)

### Additional context
I'm using .NET core 3

**Comment by Pilchie** [comment] 2019-10-28 16:55
I don't think this is extensions specific, it's just Tasks and Cancellation and async.  @stephentoub should we move to `dotnet/corfefx`?

**Comment by stephentoub** [comment] 2019-10-28 18:07
> I don't think this is extensions specific, it's just Tasks and Cancellation and async

It sounds like the OP is requesting that `Microsoft.Extensions.Hosting.Internal.Host.StopAsync` shouldn't throw a cancellation exception when cancellation occurs, and instead do something else?  The exception is coming because (assuming I'm looking at the right code) because the extensions code is explicitly calling `ThrowIfCancellationRequested`:
https://github.com/aspnet/Extensions/blob/ecc4d9fe9381ac65848968b672eb6098ec2a2cae/src/Hosting/Hosting/src/Internal/Host.cs#L75
so if that's a change in behavior that's desired, it would need to be in this extensions code to not make the above call.

**Comment by Pilchie** [comment] 2019-10-28 18:09
Thanks!  Adding @anurse to triage.

**Comment by davidfowl** [comment] 2019-10-28 18:16
It's odd we're doing that. @Tratcher do you recall why that code got added?

**Comment by Tratcher** [comment] 2019-10-28 18:29
It's trying to short circuit calling stop on all the services in case they don't honor cancelled tokens. The services will still get disposed. Note there's another call to ThrowIfCancellationRequested after the loop as well.

100 keys * 0.5s is 50 seconds, it's going to trip the default 5s shutdown timeout. Note the shutdown timeout token being tripped here is not the same one that's passed into ExecuteAsync. The ExecuteAsync token tripps when it's time to start shutting down. The sample above should honor this token to break it's foreach key loop.

**Comment by cyberhck** [comment] 2019-10-29 14:20
do you mean to say on each loop I should check if cancellation was requested and quit accordingly? Because even when I check on for loop and return if it was requested, it still throws exception,

**Comment by Tratcher** [comment] 2019-10-29 14:43
You spend 50s in this loop, you need to cancel that early.
```
                    foreach (var key in keys)
                    {
                        // make a api request, for simulation, let's do a Thread.Sleep without cancellation token
                       Thread.Sleep(500);
                    }
```

**Comment by cyberhck** [comment] 2019-10-30 09:23
even when I do that, it still throws exception, before `Thread.Sleep()` I also tried checking `if (stoppingToken.IsCancellationRequested) return;`, but behaves the exact same way,

**Comment by cyberhck** [comment] 2019-10-30 09:26
I'll try and verify again one more time maybe today evening or this weekend and update nevertheless,

**Comment by anurse** [comment] 2019-11-07 23:42
This is expected behavior when your `IHostedService` runs past the shutdown deadline. We throw in `Host.StopAsync` because the timeout elapsed while the service was shutting down.

What's the *desired* behavior here?

**Comment by cyberhck** [comment] 2019-11-08 07:47
well, even when I have ```
foreach (var key in keys)
                    {
                        // make a api request, for simulation, let's do a Thread.Sleep without cancellation token
                       Thread.Sleep(500);
                       if (stoppingToken.IsCancellationRequested) return;
                    }
```

it still throws error for some reason, I'll try to get a minimal reproduction example by this weekend, I forgot last weekend, 

desired behavior would be to stop it without throwing an exception. even though it's less than 50 seconds,

**Comment by anurse** [comment] 2019-11-08 19:36
We know why it's throwing, it's the line in Host.StopAsync here:

https://github.com/aspnet/Extensions/blob/ecc4d9fe9381ac65848968b672eb6098ec2a2cae/src/Hosting/Hosting/src/Internal/Host.cs#L75

That code is iterating through each service, calling their StopAsync and then moving on to the next one. Even when you return without throwing, that code will throw when the code moves on to the next service. 

My feeling is that it's correct to throw here. In general, any method which takes an `CancellationToken` should be expected to throw `OperationCancelledException` (most, if not all, other places in .NET do so, in my experience). In this case, the service has taken too long to shutdown, which should be an exceptional situation that would be signaled to the user.

There's also the breaking change angle. Removing an exception may break users who were using this exception for further monitoring purposes (to notify them when a hosted service runs over it's shutdown deadline).

**Comment by anurse** [comment] 2019-11-15 19:18
Closing as we're throwing by design here. Even if you terminate your hosted service's stop method without throwing, the Host's loop still throws when cancellation occurs in multiple places.

**Closed by anurse** 2019-11-15 19:18 UTC
Labels: area-hosting
