### ISSUE TITLE
Add a way to use Dependency injection in the polly policies

### ISSUE THREAD

**Issue by antonioortizpola** [aspnet/Extensions#522] opened 2018-11-05 22:40 UTC
I would like to be able to inject my logger and maybe use a entity framework context to keep log of the retries, however, i can not find a way to do it, it would be easy if the context include the service provider.

Relates to #86, but in a broad scope, talking about dependency injection in general, not just logs

**Comment by kieranbenton** [comment] 2018-11-23 22:04
QQ - the [example](https://github.com/aspnet/HttpClientFactory/issues/200#issuecomment-436791061), should that maintain the same instance of the policy between multiple HttpClient's? Because in my tests it doesn't seem to be and a new policy is being instanciated for each run albeit with the right service provider being injected. 

That causes an issue with CircuitBreaker in particular because its state isn't then shared between multiple clients.

Is that something I'm doing incorrectly, expected behaviour or a real issue?

**Comment by rynowak** [comment] 2018-12-19 00:43
Sorry for the delay, it's been a little bit chaotic with the issue/repo move here.

I'd also suggest in this case resolving the logger a single time and then closing over it rather than closing over the service provider.

@kieranbenton - yes, there are definitely cases where you want to share a policy between multiple clients. Are you saying that this is too hard to get right? or that you want to see an example of that?


@scottaddie - I think this is also something we want to add to the docs. The scenario here is when you need access to some DI services inside of a policy.

**Comment by rynowak** [comment] 2019-02-19 19:14
Closing this since docs issues are tracked elsewhere.

**Closed by rynowak** 2019-02-19 19:14 UTC
Labels: area-httpclientfactory
