### ISSUE TITLE
High memory consumption at second resolve of a service

### ISSUE THREAD

**Issue by bergermanuel** [aspnet/Extensions#970] opened 2019-01-18 09:08 UTC
Hello everyone,

we have currently a memory problem when we resolve a Controller in our .netcore Web Api. The problem occurs at in the [DynamicServiceProviderEngine](https://github.com/aspnet/Extensions/blob/3ba072c25373c19ab2cfe34483e733f3b926b2c0/src/DependencyInjection/DI/src/ServiceLookup/DynamicServiceProviderEngine.cs) at the second request. The second request calls the base class where an Expression is created and compiled. 

I think that's for optimization but I'm not sure if that's the reason why the expression is created and compiled. Maybe someone can clarify me about this part of the code. Nevertheless the memory consumption of our project rises up until 5GB at the compiling of the expression and breaks the application.

Our guess is a circular dependency but that should be detected and give a nice error message, right? Is there any limitation for the number of dependencies a class can have (directly and nested)?

**Comment by davidfowl** [comment] 2019-01-18 09:13
What does your dependency graph look like? Are they all scoped services?

**Comment by bergermanuel** [comment] 2019-01-18 09:15
We have mainly scoped services, but have also some singleton services.

**Comment by bergermanuel** [comment] 2019-01-18 09:48
When we use a different DI container like Autofac we have no problems

**Comment by davidfowl** [comment] 2019-01-18 15:38
If you can provide a repro that would be great. This might be already fixed in 3.0.

cc @pakyrm

**Comment by bergermanuel** [comment] 2019-01-22 09:05
Providing a repro is not that easy, because we cannot extract that from our code easily and don't know what's the exact problem. 

We had calls to GetService inside constructors and removed them to be resolved as a parameter but that made it even more worse. We expected some kind of circular dependency due to that that could not be detected.

We also tried to make all our services transient, that made it better, but not fixed the problem completely. 

For the moment we go with Autofac and everything works.

**Comment by pakrym** [comment] 2019-01-22 19:55
Can you take a process dump (using Task Manager - Create process dump) and share it to pakrym@microsoft.com

**Comment by pakrym** [comment] 2019-02-28 05:40
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by pakrym** 2019-02-28 05:40 UTC
Labels: area-dependencyinjection
