### ISSUE TITLE
BackgroundService TaskStatus

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Extensions#1855] opened 2019-06-17 21:06 UTC
IMHO the BackgroundService should expose the _executingTask TaskStatus so that a developer may inspect the property and determin if the service task is running and/or has been cancelled, faulted etc. 

It would also be good if the _execuringTask should also be wrapped in a try { } catch { } to capture background service expections as a additonal property with the option to rethrow the expectation or call an optional function when and expection occurs

**Comment by khellang** [comment] 2019-06-17 21:17
I'm not sure what scenario this would enable. Do you have an example?

When you implement `ExecuteAsync` you return a `Task` that you literally control the status of. There should be no reason to expose a field for you to inspect.

**Comment by davidfowl** [comment] 2019-06-17 22:11
Closing as dupe of https://github.com/aspnet/Extensions/issues/1857

**Closed by davidfowl** 2019-06-17 22:11 UTC
Labels: area-hosting
