### ISSUE TITLE
Microsoft.Extensions.Configuration.AzureAppConfiguration prevents migration to C# 8 async streams

### ISSUE THREAD

**Issue by danielcweber** [aspnet/Extensions#2548] opened 2019-10-22 08:25 UTC
You might say: Microsoft.Extensions.Configuration.AzureAppConfiguration is not even part of this repo. Well it should be. I'd happily offer a PR for this issue if it was. 

Issue: It references System.Interactive.Async 3.1.1. If projects evolve to use the new C# 8 async stream feature, they are likely to use v4.0.0 of System.Interactive.Async. These packages cannot coexist, the IEnumera(xyz) interfaces are incompatible. So we end up with exceptions like this: 

System.MissingMethodException : Method not found: 'System.Collections.Generic.IAsyncEnumerable`1<http://Microsoft.Azure.AppConfiguration.Azconfig.IKeyValue> http://Microsoft.Azure.AppConfiguration.Azconfig.AzconfigClient.GetKeyValues(https://t.co/Sfw4eyJdZU.AppConfiguration.Azconfig.QueryKeyValueCollectionOptions)'.
  Stack Trace: 
    AzureAppConfigurationProvider.LoadAll()
    AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
    AzureAppConfigurationProvider.LoadAll()
    AzureAppConfigurationProvider.Load()
    ConfigurationRoot.ctor(IList`1 providers)
    http://ConfigurationBuilder.Build()

**Comment by drago-draganov** [comment] 2019-10-22 08:40
Duplicate of https://github.com/Azure/AppConfiguration/issues/139

**Closed** 2019-10-22 08:43 UTC
