### ISSUE TITLE
can not have entries that the key contains column in appsettings.json 

### ISSUE THREAD

**Issue by Eilon** [aspnet/Extensions#911] opened 2019-01-08 17:27 UTC
_From @NathanYukai on Wednesday, 02 January 2019 13:45:32_

# Detail
for an setting like the following:

```json
{
  "settings":{
    "key:test-key" : true
  }
}
```

when reading the `configuration.GetSection("settings").GetChildren()`, it read "key" as the key , instead of "key:test-key"

I have this issue with .net core 2.0, haven't test on other version yet.

_Copied from original issue: dotnet/core#2197_

**Comment by poke** [comment] 2019-01-13 02:11
I believe this is by design. The colon is used by the configuration framework to separate segments in configuration paths. Since configuration is in the end just a key value store where the keys are more complex paths that are segments joined by colons, there isn’t really a difference between a key `key:test-key` and a path `key:test-key`.

Since the JSON provider will flatten the structure to construct the configuration paths, there is no real way to differentiate between a key that originally contained a colon and a path with two segments.

Also, if a path segment was allowed to have a colon as part of its (single) key, then there would be no way this could be reliably bound to a property name (since configuration is usually used in a bound way, e.g. through the options pattern).

**Comment by ajcvickers** [comment] 2019-04-18 17:58
Closing as this is by-design.

**Closed by ajcvickers** 2019-04-18 17:58 UTC
Labels: area-config
