### ISSUE TITLE
Generic Host throws exception on Xamarin Android

### ISSUE THREAD

**Issue by tomstreet** [aspnet/Extensions#2182] opened 2019-08-12 16:32 UTC
### Describe the bug
Not sure if this a supported scenario, but I'm trying to use all the goodness of the generic host in a Xamarin Android app so I get the DI, logging and http client factory. This issue only happens on Xamarin Android - everything works fine on iOS.

A `System.ArgumentException` gets thrown upon calling `Build()` on the `HostBuilder` with the message `"The path must be absolute. Parameter name: root"`.

### To Reproduce
Visual Studio: v16.2.1
Xamarin: 16.2.0.91
Xamarin Android SDK: 9.4.1.0
Microsoft.Extensions.Hosting 3.0.0-preview7.19362.4

1 - File > New > Xamarin Andorid App
2 - Added `var host = new HostBuilder().Build()` to top of the `OnCreate` method in `MainActivity`
3 - Ran on Android 9.0 emulator

I managed to work around it by setting the `HostDefaults.ContentRootKey`:

```csharp
var root = Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal), "root");
Directory.CreateDirectory(root);

var hostBuilder = new HostBuilder()
    .ConfigureHostConfiguration(c =>
    {
        c.AddInMemoryCollection(new Dictionary<string, string>
        {
            { HostDefaults.ContentRootKey, root }
        });
    }).Build();

```
### Expected behavior
I expected it to give me an instance of an `IHost`

**Comment by kant2002** [comment] 2019-10-06 10:13
Right now this is not even compiled for me with 3.0 RTM @Eilon any ideas how Generic Host can be used inside Xamarin?

**Comment by Eilon** [comment] 2019-10-07 16:52
I've used Generic Host just fine in Xamarin on Android (emulator). But, I didn't specifically try to use any config features.

I have code like this:

```c#
            var host = Host.CreateDefaultBuilder()
                .ConfigureServices((hostContext, services) =>
                {
                    // Register app-specific services
                    services.AddSingleton<AppState>();
                })
                .Build();

            // Now do stuff with the host:
            var someService = host.Services.GetService<IFooService>();
```

And then I do stuff with various services, and I've had no problem with it.

**Comment by kant2002** [comment] 2019-10-07 17:11
@Eilon can you check this one project. https://github.com/kant2002/XamringGenericHostNetCoreIssue/blob/master/App4/App4.csproj#L124-L126 I highlighted only one changes in the code from the template. For me even adding reference does not work. not even creation of the Host.

**Comment by kant2002** [comment] 2019-10-07 17:20
```
1>------ Build started: Project: App4, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>  App4 -> D:\d\kant\my\App4\App4\bin\Debug\App4.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1824,2): warning XA0107: Ignoring  as it is a Reference Assembly
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1824,2): warning XA0107: Ignoring  as it is a Reference Assembly
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1824,2): warning XA0107: Ignoring  as it is a Reference Assembly
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1824,2): warning XA0107: Ignoring  as it is a Reference Assembly
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1824,2): error XA2002: Can not resolve reference: `System.Diagnostics.EventLog`, referenced by `Microsoft.Extensions.Logging.EventLog`. Please add a NuGet package or assembly reference for `System.Diagnostics.EventLog`, or remove the reference to `Microsoft.Extensions.Logging.EventLog`.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1824,2): error XA2002: Can not resolve reference: `Microsoft.Bcl.AsyncInterfaces`, referenced by `System.Text.Json`. Please add a NuGet package or assembly reference for `Microsoft.Bcl.AsyncInterfaces`, or remove the reference to `System.Text.Json`.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Here the public build 
https://codevision.visualstudio.com/OpenSourceQuircks/_build/results?buildId=13058&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9
It has slightly different errors, but it is on Mac, maybe that's the issue.

**Comment by Eilon** [comment] 2019-10-07 21:16
OK I'm genuinely not sure what's wrong here. I tried in my own project and I can use Generic Host just fine in a Xamarin Android project. My previous project was a Xamarin.Forms project, which worked fine, but I tried Xamarin Android and it worked fine too.

I downloaded your project and it compiles and runs fine on my machine. Both our projects were using the same versions of all the NuGet packages.

So, I'm guessing the difference is that you and I are using different tools/SDK in use. I'm running Windows 10 w/ VS for Windows 16.3 and everything works fine. I also have .NET Core 3.0 installed, in case maybe that affects how these packages are used.

Maybe try going to https://dot.net/ and installing the .NET Core 3.0, and also make sure you have the latest Visual Studio updates, and try again?

**Comment by kant2002** [comment] 2019-10-26 18:36
I reinstall .NET Core 3.0 and VS (which was 16.3 latest). Azure DevOps build was on Mac and produce similar error. I trying with 3.1 Preview as well and one Hosting.Abstractions how added to the list of assemblies which prevent project from compilation.

**Comment by Eilon** [comment] 2019-10-28 16:37
> Hosting.Abstractions how added to the list of assemblies which prevent project from compilation.

@kant2002 can you show what error you were getting for this?

**Comment by kant2002** [comment] 2019-10-28 18:08
It is same as `error XA2002: Can not resolve reference:
`Microsoft.Bcl.AsyncInterfaces`, referenced by `System.Text.Json`. Please
add a NuGet package or assembly reference for
`Microsoft.Bcl.AsyncInterfaces`, or remove the reference to
`System.Text.Json`.` but with Hosting.Abstractions instead of
Sustem.Text.Json. Explicitly adding that M.Bcl.AsyncInterfaces package to
main project does not helps.

**Comment by Eilon** [comment] 2019-10-29 04:27
@kant2002 sorry I'm not sure what's going on because I'm unable to reproduce this problem. I'll let the experts in this repo take it from here.

**Comment by anurse** [comment] 2019-11-07 23:47
Going back to the original issue, @tomstreet , the Content Root Path can be set manually using `.UseContentRoot` on the `IHostBuilder`. It's entirely likely that the default logic (which uses `Directory.GetCurrentDirectory`) could be broken on Xamarin. I'm going to close this as we don't have plans to add content root behavior for Xamarin right now. There is some discussion of larger support for Xamarin in Generic Host/Extensions and we'll cover this when we do that.

@kant2002 I'd suggest filing a separate issue for that and include the repro steps and your repro project. It's not quite the same issue as the one here since it's a compilation problem.

**Closed by anurse** 2019-11-07 23:47 UTC
Labels: area-hosting
