### ISSUE TITLE
Issue with CookieContainer when use HttpClientFactory

### ISSUE THREAD

**Issue by uyquoc** [aspnet/Extensions#872] opened 2018-12-27 03:55 UTC
### Describe the bug
`HttpClient` objects which are created from `HttpClientFactory` may use the same pooled `HttpClientHandler` object, so they may use the same `CookieContainer` object. This causes a thread-safe issue.

### To Reproduce
Assume we have a web application call to api/Token (GET) of API server.

Web:
```c#
       public async Task<string> GetToken()

        {
            var httpClient = _clientFactory.CreateClient();
            var response = await httpClient.GetAsync("http://api.local:5089/api/token");
            var token = await response.Content.ReadAsStringAsync();
            return token;
        }
```

API:
```c#
        public ActionResult<string> Get()
        {   
            string token = HttpContext.Request.Cookies.ContainsKey("Token") ? 
                           HttpContext.Request.Cookies["Token"] : Guid.NewGuid().ToString();
            
            HttpContext.Response.Cookies.Append("Token", token);
            return token;
        }
```

Step 1: Make the first request to API, in Web application, `response.Headers.GetValues("Set-Cookies")` will show "Token" cookie's value equals "abc"
Step 2: Make a second request to API, in Web application, `response.Headers.GetValues("Set-Cookies")` will show "Token" cookie's value also equals "abc"

### Expected behavior
`HttpClient` objects which are created by `HttpClientFactory` should have the same behavior as creating new `HttpClient`

If we use `new HttpClient()`, each request to API, we will get new Token value, but we cannot achieve this 
purpose with `HttpClientFatory`. How could we deal with this problem when we have to use Cookie in API?

**Comment by LeaFrock** [comment] 2019-05-22 06:53
Oh God. Still no answers from last year...

**Comment by manigandham** [comment] 2019-05-22 14:26
You can configure the underlying `HttpMessageHandler` to not use a cookie container, which means you have to then handle the cookies yourself from the headers.

```csharp
services.AddHttpClient("default")
    .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
    {
        AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate, 
        AllowAutoRedirect = true,
        UseCookies = false
    });
```

**Comment by mt89vein** [comment] 2019-05-22 17:00
i got an example for self-handling cookies from the headers: https://gist.github.com/mt89vein/9c9d7291d42dac0d1598f1a61da3117c
It may be useful for someone.

**Comment by zvirja** [comment] 2019-05-28 08:34
If you don't want to control `HttpClientHandler` activation, you can use alternative workaround:

```c#
services
    .AddHttpClient(...)
    .ConfigureHttpMessageHandlerBuilder(builder =>
    {
        if (builder.PrimaryHandler is HttpClientHandler handler)
        {
            handler.UseCookies = false;
        }
    });
```

**Comment by rynowak** [comment] 2019-11-24 22:12
This seems like something we should add to the documentation. It's definitely by design that the factory reuses the message handler.

**Comment by rynowak** [comment] 2019-11-24 23:44
Closing this, I've created an issue and PR on the docs repo.

**Closed by rynowak** 2019-11-24 23:44 UTC
Labels: area-httpclientfactory
